// CRMS System Roles
export const ROLE_CRMS_CORE_USER = "ROLE_CRMS_CORE_USER";
export const ROLE_CRMS_READONLY_USER = "ROLE_CRMS_READONLY_USER";
export const ROLE_CRMS_PSO_MANAGER = "ROLE_CRMS_PSO_MANAGER";
export const ROLE_CRMS_DATA_USER = "ROLE_CRMS_DATA_USER";
export const ROLE_CRMS_SYS_ADMIN = "ROLE_CRMS_SYS_ADMIN";
